# Generated by Django 6.0.4 on 2026-09-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscription_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('paid', 'Платный')], default='free', max_length=10, verbose_name='Тариф'),
        ),
    ]
