# Generated by Django 6.0.4 on 2026-05-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_paid_subscribers_remove_user_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monetizations',
            field=models.BooleanField(default=False, verbose_name='Монетизация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='price_month',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3, verbose_name='Стоимость в месяц'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=40, verbose_name='Ссылка на сайт'),
        ),
    ]
