# Generated by Django 6.0.4 on 2026-07-26 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_name',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Укажите только ник Telegram (5–20 символов: латиница, цифры, _)', regex='^[A-Za-z0-9_]{5,20}$')], verbose_name='Телеграм'),
        ),
    ]
