# Generated by Django 6.0.4 on 2026-07-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['position', 'created_at'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='postimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
