# Generated by Django 6.0.4 on 2026-05-01 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_rename_published_post_is_published_and_more'),
        ('users', '0002_remove_user_paid_subscribers_remove_user_subscribers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('new_subscriber', 'New subscriber'), ('new_like', 'New like'), ('new_comment', 'New comment'), ('new_post', 'New post')])),
                ('text', models.TextField()),
                ('image_url', models.URLField()),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.post')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
