# Generated by Django 6.0.4 on 2026-09-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_subscriber', 'Новый подписчик'), ('new_like', 'Новый лайк'), ('new_comment', 'Новый комментарий'), ('new_post', 'Новый пост')], verbose_name='Тема'),
        ),
    ]
